---

- hosts: all
  become: true
  tasks:

  - name: install apache package and php on Linux
    yum:
      name:
       - httpd
       - php
      state: present
      update_cache: yes
    when: ansible_distribution == "Amazon Linux"

  - name: install apache and php on Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

 
